### ISSUE TITLE
Reuse Analysis Roadmap

### ISSUE THREAD

**Issue by SchrodingerZhu** [SchrodingerZhu/rura#8]
- [ ] Basic type inference for LIR 
   - [x] Decide how frontend passes external definitions to backend 
   - [x] Decide the interface of analysis pass
- [ ] `drop/clone` Insertion
   - [ ] Simple liveness & lifetime analysis (this is simple as we won't allow multiple borrow and all borrow appears at function call to FFI)
   - [ ] Insert clone if a value  is used more than one times (based on type info)
   - [ ] Insert drop at the frontier of liveness range
- [ ] Reuse Token Pairing
   - [ ] Same-type heuristic (should use existing `Shape`)
   - [ ] (optional) Leave design space for future (see if we profile the reuse probability and improve the codegen; benefit may be limited)
- [ ] Special Case Optimization
   - [ ] Inplace Mutation: After unwrap, most value are unchanged, some values are updated then fill back to the same constructor 
   - [ ] Fixpoint: After unwrap, exactly the same constructor is returned without any change.
   - [ ] Ref: After unwrap, all values are either directly dropped or pass to another function by reference.  (need to think about the implication to larger RSS)
- (optional) Lazy Allocation Optimization
   - [ ] On a failure path of reuse analysis, if we know that a value is possibly unchanged, we insert a check to the address and return the original value if it is really unchanged. (still need to think about the soundness/decide how to propagate function level information)
